## PANDAS PRACTICE

### Accessing Data

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
nba = pd.read_csv(r"C:\Users\jyoti\Documents\DA Course FB\Excel\Files\nba.csv")

In [4]:
nba = pd.DataFrame(nba)

In [5]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Selecting a Column or multiple columns using the name of the columns
nba[["Name","Age","Team","Position"]]

              Name   Age            Team Position
0    Avery Bradley  25.0  Boston Celtics       PG
1      Jae Crowder  25.0  Boston Celtics       SF
2     John Holland  27.0  Boston Celtics       SG
3      R.J. Hunter  22.0  Boston Celtics       SG
4    Jonas Jerebko  29.0  Boston Celtics       PF
..             ...   ...             ...      ...
453   Shelvin Mack  26.0       Utah Jazz       PG
454      Raul Neto  24.0       Utah Jazz       PG
455   Tibor Pleiss  26.0       Utah Jazz        C
456    Jeff Withey  26.0       Utah Jazz        C
457            NaN   NaN             NaN      NaN

[458 rows x 4 columns]

In [7]:
# Selecting rows using .loc method (label-based selection)

data = pd.read_csv(r"C:\Users\jyoti\Documents\DA Course FB\Excel\Files\nba.csv",index_col = "Name")# using Name as index instead of the numberdata
data.loc["John Holland"]

Team           Boston Celtics
Number                   30.0
Position                   SG
Age                      27.0
Height                    6-5
Weight                  205.0
College     Boston University
Salary                    NaN
Name: John Holland, dtype: object

In [8]:
# Using iloc[]: using interger like positions for indexing

print(data.iloc[3:6])
print(data.iloc[6])

                         Team  Number Position   Age Height  Weight  \
Name
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0

                     College      Salary
Name
R.J. Hunter    Georgia State   1148640.0
Jonas Jerebko            NaN   5000000.0
Amir Johnson             NaN  12000000.0
Team        Boston Celtics
Number                55.0
Position                PF
Age                   21.0
Height                 6-8
Weight               235.0
College                LSU
Salary           1170960.0
Name: Jordan Mickey, dtype: object

### Working with Missing Values

In [9]:
#isnull()

data.isnull().sum()

Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [10]:
data.notnull().sum()
# Shows all the not null values

Team        457
Number      457
Position    457
Age         457
Height      457
Weight      457
College     373
Salary      446
dtype: int64

In [11]:
import numpy as np
 
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
df = pd.DataFrame(dict)

In [12]:
df

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [13]:
# filling the NA values with a specific value, in this case 0
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [14]:
# We can also drop the NA values using dropna() will drop all rows with even a singular NAN value

df.dropna()

   First Score  Second Score  Third Score
1         90.0          45.0         40.0

### Iteration of Rows and Columns

In [15]:
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
df_iter = pd.DataFrame(dict)

df_iter

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [16]:
# iterrows() will return (index,row) which is why we will be using both i and j in our for loop

for i,j in df_iter.iterrows():
    print(i,j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object

In [17]:
# iterrating Columns

for label,values in df_iter.items():
    print(f"Column:",label)
    print(values)
    print()

Column: name
0    aparna
1    pankaj
2    sudhir
3     Geeku
Name: name, dtype: object

Column: degree
0       MBA
1       BCA
2    M.Tech
3       MBA
Name: degree, dtype: object

Column: score
0    90
1    40
2    80
3    98
Name: score, dtype: int64

### Series.apply()

In [18]:
a = pd.Series([2,4,6,8])
b = a.apply(lambda x: x / 2, convert_dtype = True)

print(b)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [19]:
#classify each mark in the Series as Pass or Fail based on a condition.

marks = pd.Series([98,76,54,100,43])

def f(x):
    return "pass" if x > 75 else "fail"

result = marks.apply(f)

print(result)

0    pass
1    pass
2    fail
3    pass
4    fail
dtype: object

In [20]:
#  lambda function to increase each salary value in the Series by 10%.

salary = pd.Series([10000, 12000, 50000])

hike = salary.apply(lambda x: x * 1.10)

print(hike)

0    11000.0
1    13200.0
2    55000.0
dtype: float64

# Data Cleaning

## Handling Missing Values

In [3]:
# loading another Dataset to practice cleaning
employees = pd.read_csv(r"C:\Users\jyoti\Documents\DA Course FB\Excel\Files\employees.csv")

employees = pd.DataFrame(employees)

In [4]:
employees.isnull().sum()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [5]:
# Filtering out non-missing values

nmg = pd.notnull(employees["Gender"])

nmgd = employees[nmg]

nmgd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [6]:
employees.shape

(1000, 8)

## Filling NaN Values

In [7]:
# Filling the NaN values with "No gender"

employees['Gender'].fillna("No Gender", inplace = True)

employees["Gender"].isnull().sum()

0

In [8]:
employees[10:30]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,No Gender,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,No Gender,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services
25,NaN,Male,10/8/2012,1:12 AM,37076,18.576,NaN,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,No Gender,7/11/1991,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal

In [9]:
employees["Team"] = employees["Team"].replace(to_replace = np.nan, value ="Team Unspecified")

In [10]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Team Unspecified
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,No Gender,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

###  Dropping NaN Values

#### Dropping rows with atleat one null value

In [11]:
employees.dropna()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Team Unspecified
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,No Gender,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

#### Dropping Rows with ALL null values

In [12]:
employees.dropna(how = "all")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Team Unspecified
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,No Gender,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

#### Dropping Columns with atleast one null value

In [13]:
employees.dropna(axis = 1)

,Gender,Start Date,Last Login Time,Salary,Bonus %,Team
0,Male,8/6/1993,12:42 PM,97308,6.945,Marketing
1,Male,3/31/1996,6:53 AM,61933,4.170,Team Unspecified
2,Female,4/23/1993,11:17 AM,130590,11.858,Finance
3,Male,3/4/2005,1:00 PM,138705,9.340,Finance
4,Male,1/24/1998,4:47 PM,101004,1.389,Client Services
...,...,...,...,...,...,...
995,No Gender,11/23/2014,6:09 AM,132483,16.655,Distribution
996,Male,1/31/1984,6:30 AM,42392,19.675,Finance
997,Male,5/20/2013,12:39 PM,96914,1.421,Product
998,Male,4/20/2013,4:45 PM,60500,11.985,Business Development
999,Male,5/15/2012,6:24 PM,129949,10.169,Sales

## Dropping Duplicates

In [14]:
employees.drop_duplicates()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Team Unspecified
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,No Gender,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

#### Dropping duplicated based on specific columns

In [15]:
employees.drop_duplicates(subset = "First Name")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Team Unspecified
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
712,Martin,No Gender,2/6/2001,4:17 AM,123963,15.745,True,Engineering
749,Janet,No Gender,1/25/1986,5:48 AM,85789,9.712,False,Legal
832,Keith,Male,2/12/2003,3:02 PM,120672,19.467,False,Legal
855,Phillip,No Gender,10/20/2003,11:09 AM,89700,2.277,True,Team Unspecified
887,David,Male,12/5/2009,8:48 AM,92242,15.407,False,Legal

#### Keeping the last occurrence of the duplicates

In [16]:
employees.drop_duplicates(keep = 'last')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Team Unspecified
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,No Gender,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

## Changing Data Types if Required

#### Using .astype()

In [17]:
employees.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [18]:
employees["Salary"] = employees["Salary"].astype(float)

## Dropping Columns with Empty Values

In [19]:
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan
print(df)

nan_value = float("NaN")
df.replace("", nan_value, inplace=True)

df.dropna(how='all', axis=1, inplace=True)

df

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName  Age
0     Vipul    0
1    Ashish    0
2     Milan    0

## String Manipulation using Pandas

In [20]:


data = { 'Name': ['Lukas', 'Sofia', 'Hiroshi', 'Marta', 'Yannis', np.nan, 'Elena'],
         'City': ['Berlin', 'Madrid', 'Tokyo', 'Warsaw', 'Athens', 'Oslo', 'Lisbon'] }

df_new = pd.DataFrame(data)
print(df_new)

      Name    City
0    Lukas  Berlin
1    Sofia  Madrid
2  Hiroshi   Tokyo
3    Marta  Warsaw
4   Yannis  Athens
5      NaN    Oslo
6    Elena  Lisbon

In [21]:
df_new.dtypes
# Since they are all objects, lets change their dtype to string

Name    object
City    object
dtype: object

In [22]:
df_new = df_new.astype("string")

In [23]:
df_new.dtypes

Name    string[python]
City    string[python]
dtype: object

In [24]:
print(df_new['Name'].str.lower())

0      lukas
1      sofia
2    hiroshi
3      marta
4     yannis
5       <NA>
6      elena
Name: Name, dtype: string

In [25]:
print(df_new['Name'].str.upper())

0      LUKAS
1      SOFIA
2    HIROSHI
3      MARTA
4     YANNIS
5       <NA>
6      ELENA
Name: Name, dtype: string

In [26]:
# remove unwanted traling Spaces 
print(df_new['Name'].str.strip())

0      Lukas
1      Sofia
2    Hiroshi
3      Marta
4     Yannis
5       <NA>
6      Elena
Name: Name, dtype: string

In [27]:
# Splits string into a list of parts seperated by the separator specified
print(df_new['Name'].str.split('a'))

0     [Luk, s]
1     [Sofi, ]
2    [Hiroshi]
3    [M, rt, ]
4    [Y, nnis]
5         <NA>
6     [Elen, ]
Name: Name, dtype: object

In [28]:
# Length of the String
print(df_new['City'].str.len())

0    6
1    6
2    5
3    6
4    6
5    4
6    6
Name: City, dtype: Int64

In [29]:
# concatenates all strings using the specifies operator
print(df_new['City'].str.cat(sep = ','))

Berlin,Madrid,Tokyo,Warsaw,Athens,Oslo,Lisbon

In [30]:
# one-hot encoding for Machine Learning
print(df_new['City'].str.get_dummies())

   Athens  Berlin  Lisbon  Madrid  Oslo  Tokyo  Warsaw
0       0       1       0       0     0      0       0
1       0       0       0       1     0      0       0
2       0       0       0       0     0      1       0
3       0       0       0       0     0      0       1
4       1       0       0       0     0      0       0
5       0       0       0       0     1      0       0
6       0       0       1       0     0      0       0

In [31]:
print(df_new["Name"].str.startswith('L'))

0     True
1    False
2    False
3    False
4    False
5     <NA>
6    False
Name: Name, dtype: boolean

In [32]:
print(df_new["Name"].str.endswith('a'))

0    False
1     True
2    False
3     True
4    False
5     <NA>
6     True
Name: Name, dtype: boolean

In [33]:
# used to replace a string with another 
print(df_new['Name'].str.replace('Elena','Emily'))

0      Lukas
1      Sofia
2    Hiroshi
3      Marta
4     Yannis
5       <NA>
6      Emily
Name: Name, dtype: string

In [34]:
# this method duplicates Each string a given number of times
print(df_new['City'].str.repeat(4))

0    BerlinBerlinBerlinBerlin
1    MadridMadridMadridMadrid
2        TokyoTokyoTokyoTokyo
3    WarsawWarsawWarsawWarsaw
4    AthensAthensAthensAthens
5            OsloOsloOsloOslo
6    LisbonLisbonLisbonLisbon
Name: City, dtype: string

In [35]:
# this method counts how many times a specifies substring or pattern appears in each string
print(df_new['Name'].str.count('a'))

0       1
1       1
2       0
3       2
4       1
5    <NA>
6       1
Name: Name, dtype: Int64

In [36]:
# this returns a list of all the occurances/patterns given
print(df_new['Name'].str.findall('a'))

0       [a]
1       [a]
2        []
3    [a, a]
4       [a]
5      <NA>
6       [a]
Name: Name, dtype: object

In [37]:
# checks if string is lowercase
print(df_new['City'].str.islower())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
Name: City, dtype: boolean

In [38]:
print(df_new['City'].str.isupper())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
Name: City, dtype: boolean

In [39]:
print(df_new['City'].str.isnumeric())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
Name: City, dtype: boolean

In [40]:
# this method swaps uppercase withlowercase string values
print(df_new['City'].str.swapcase())

0    bERLIN
1    mADRID
2     tOKYO
3    wARSAW
4    aTHENS
5      oSLO
6    lISBON
Name: City, dtype: string

## Data Processing with Pandas

In [41]:
# using describe to get statistical info about the dataframe
employees.describe()

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000

In [42]:
# Sorting by a single Columns
employees.sort_values(by = 'Salary', ascending = False).head(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
644,Katherine,Female,8/13/1996,12:21 AM,149908.0,18.912,False,Finance
429,Rose,Female,5/28/2015,8:40 AM,149903.0,5.630,False,Human Resources
828,Cynthia,Female,7/12/2006,8:55 AM,149684.0,7.864,False,Product
186,NaN,Female,2/23/2005,9:50 PM,149654.0,1.825,NaN,Sales
160,Kathy,Female,3/18/2000,7:26 PM,149563.0,16.991,True,Finance
740,Russell,No Gender,5/9/2009,11:59 AM,149456.0,3.533,False,Marketing
793,Andrea,Female,7/22/1999,9:25 AM,149105.0,13.707,True,Distribution
981,James,Male,1/15/1993,5:19 PM,148985.0,19.280,False,Legal
800,Clarence,Male,8/5/1989,6:11 PM,148941.0,11.517,False,Product
844,Maria,No Gender,6/19/1985,1:48 AM,148857.0,8.738,False,Legal

In [43]:
# Sorting by Multiple Columns
employees.sort_values(by = ['Salary','Bonus %'], ascending = False)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
644,Katherine,Female,8/13/1996,12:21 AM,149908.0,18.912,False,Finance
429,Rose,Female,5/28/2015,8:40 AM,149903.0,5.630,False,Human Resources
828,Cynthia,Female,7/12/2006,8:55 AM,149684.0,7.864,False,Product
186,NaN,Female,2/23/2005,9:50 PM,149654.0,1.825,NaN,Sales
160,Kathy,Female,3/18/2000,7:26 PM,149563.0,16.991,True,Finance
...,...,...,...,...,...,...,...,...
650,Cynthia,Female,7/5/1986,1:24 AM,35381.0,11.749,False,Finance
63,Matthew,Male,1/2/2013,10:33 PM,35203.0,18.040,False,Human Resources
82,Steven,Male,3/30/1980,9:20 PM,35095.0,8.379,True,Client Services
238,Kevin,Male,3/25/1982,7:31 AM,35061.0,5.128,False,Legal
576,Michael,Male,7/30/1993,5:35 PM,35013.0,14.879,False,Product

In [44]:
# using the apply function
def extra(value):
    if value > 100000:
        return "Yes"
    else:
        return "No"
    
employees['Extra Bonus'] = employees['Salary'].apply(extra)

employees.tail()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Extra Bonus
995,Henry,No Gender,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution,Yes
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance,No
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product,No
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development,No
999,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales,Yes