# Data Manipulation with Pandas

### Creating a DataFrame

In [57]:
import pandas as pd

In [58]:
# Create a DF object
students = pd.DataFrame()

In [59]:
# assigning Values to rows and columns of the Data Frame
students['Name'] = ['Tanaya','Mansi','Jenil','Nirav']
students['Age'] = [24, 26, 23, 20]
students['Student'] = [True, False, True, True]

students

     Name  Age  Student
0  Tanaya   24     True
1   Mansi   26    False
2   Jenil   23     True
3   Nirav   20     True

### Adding Data Using pd.concat()

In [60]:
#  adding a new row means creating a new series object and appending it to the dataframe

new_student = {'Name':'Mahek','Age': 22, 'Student' : True}

In [61]:
students = pd.concat([students, pd.DataFrame([new_student])], ignore_index = True)

In [62]:
students

     Name  Age  Student
0  Tanaya   24     True
1   Mansi   26    False
2   Jenil   23     True
3   Nirav   20     True
4   Mahek   22     True

### Getting the Dimensions and Basic Info of the DataFrame

In [63]:
print("Dimensions of the DataFrame :", students.shape)
print("----------------------")
print("Basic Info :", students.info())
print("----------------------")
print("Correlation :")
print(students.corr(numeric_only = True))

Dimensions of the DataFrame : (5, 3)
----------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      int64
 2   Student  5 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 217.0+ bytes
Basic Info : None
----------------------
Correlation :
          Age  Student
Age      1.00    -0.75
Student -0.75     1.00

### Dropping Columns

In [64]:
# always use axis = 1 for columns
students = students.drop('Student', axis = 1)

### Dropping Rows

In [65]:
# always use axis = 0 for rows
students = students.drop(3, axis = 0)

In [66]:
students

     Name  Age
0  Tanaya   24
1   Mansi   26
2   Jenil   23
4   Mahek   22

### Groupby()

#### 1. Grouping by one column

In [67]:
nba = pd.read_csv(r"C:\Users\jyoti\Documents\DA Course FB\Excel\Files\nba.csv")

In [68]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [72]:
# lets group the data by team and calculate the total points scored by each team
team = nba.groupby('Team')
print(team.first()) # this prints the first entries in each group formed

                                         Name  Number Position   Age Height  \
Team
Atlanta Hawks                   Kent Bazemore    24.0       SF  26.0    6-5
Boston Celtics                  Avery Bradley     0.0       PG  25.0    6-2
Brooklyn Nets                Bojan Bogdanovic    44.0       SG  27.0    6-8
Charlotte Hornets               Nicolas Batum     5.0       SG  27.0    6-8
Chicago Bulls                Cameron Bairstow    41.0       PF  25.0    6-9
Cleveland Cavaliers       Matthew Dellavedova     8.0       PG  25.0    6-4
Dallas Mavericks              Justin Anderson     1.0       SG  22.0    6-6
Denver Nuggets                 Darrell Arthur     0.0       PF  28.0    6-9
Detroit Pistons                  Joel Anthony    50.0        C  33.0    6-9
Golden State Warriors         Leandro Barbosa    19.0       SG  33.0    6-3
Houston Rockets                  Trevor Ariza     1.0       SF  30.0    6-8
Indiana Pacers                    Lavoy Allen     5.0       PF  27.0    6-9
Los Angeles Clippers             Cole Aldrich    45.0        C  27.0   6-11
Los Angeles Lakers               Brandon Bass     2.0       PF  31.0    6-8
Memphis Grizzlies                Jordan Adams     3.0       SG  21.0    6-5
Miami Heat                         Chris Bosh     1.0       PF  32.0   6-11
Milwaukee Bucks         Giannis Antetokounmpo    34.0       SF  21.0   6-11
Minnesota Timberwolves        Nemanja Bjelica    88.0       PF  28.0   6-10
New Orleans Pelicans            Alexis Ajinca    42.0        C  28.0    7-2
New York Knicks                 Arron Afflalo     4.0       SG  30.0    6-5
Oklahoma City Thunder            Steven Adams    12.0        C  22.0    7-0
Orlando Magic                  Dewayne Dedmon     3.0        C  26.0    7-0
Philadelphia 76ers                Elton Brand    42.0       PF  37.0    6-9
Phoenix Suns                     Eric Bledsoe     2.0       PG  26.0    6-1
Portland Trail Blazers        Cliff Alexander    34.0       PF  20.0    6-8
Sacramento Kings                   Quincy Acy    13.0       SF  25.0    6-7
San Antonio Spurs           LaMarcus Aldridge    12.0       PF  30.0   6-11
Toronto Raptors               Bismack Biyombo     8.0        C  23.0    6-9
Utah Jazz                       Trevor Booker    33.0       PF  28.0    6-8
Washington Wizards              Alan Anderson     6.0       SG  33.0    6-6

                        Weight                College      Salary
Team
Atlanta Hawks            201.0           Old Dominion   2000000.0
Boston Celtics           180.0                  Texas   7730337.0
Brooklyn Nets            216.0         Oklahoma State   3425510.0
Charlotte Hornets        200.0  Virginia Commonwealth  13125306.0
Chicago Bulls            250.0             New Mexico    845059.0
Cleveland Cavaliers      198.0           Saint Mary's   1147276.0
Dallas Mavericks         228.0               Virginia   1449000.0
Denver Nuggets           235.0                 Kansas   2814000.0
Detroit Pistons          245.0                   UNLV   2500000.0
Golden State Warriors    194.0         North Carolina   2500000.0
Houston Rockets          215.0                   UCLA   8193030.0
Indiana Pacers           255.0                 Temple   4050000.0
Los Angeles Clippers     250.0                 Kansas   1100602.0
Los Angeles Lakers       250.0                    LSU   3000000.0
Memphis Grizzlies        209.0                   UCLA   1404600.0
Miami Heat               235.0           Georgia Tech  22192730.0
Milwaukee Bucks          222.0                Arizona   1953960.0
Minnesota Timberwolves   240.0             Louisville   3950001.0
New Orleans Pelicans     248.0             California   4389607.0
New York Knicks          210.0                   UCLA   8000000.0
Oklahoma City Thunder    255.0             Pittsburgh   2279040.0
Orlando Magic            245.0                    USC    947276.0
Philadelphia 76ers       254.0                   Duke    947276.0
Phoenix Suns             190.0               Kentucky  13500000.0
Portland Trail Blazers   240.0                 Kansas    525093.0
Sacramento Kings         240.0                 Baylor    981348.0
San Antonio Spurs        240.0                  Texas  19689000.0
Toronto Raptors          245.0               Missouri   2814000.0
Utah Jazz                228.0                Clemson   4775000.0
Washington Wizards       220.0         Michigan State   4000000.0

In [35]:
team.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0

#### 2. Grouping by Mutiple columns

In [37]:
grouping = nba.groupby(['Team','Position'])
print(grouping.first())

                                         Name  Number   Age Height  Weight  \
Team               Position
Atlanta Hawks      C               Al Horford    15.0  30.0   6-10   245.0
                   PF          Kris Humphries    43.0  31.0    6-9   235.0
                   PG         Dennis Schroder    17.0  22.0    6-1   172.0
                   SF           Kent Bazemore    24.0  26.0    6-5   201.0
                   SG        Tim Hardaway Jr.    10.0  24.0    6-6   205.0
...                                       ...     ...   ...    ...     ...
Washington Wizards C            Marcin Gortat    13.0  32.0   6-11   240.0
                   PF             Drew Gooden    90.0  34.0   6-10   250.0
                   PG          Ramon Sessions     7.0  30.0    6-3   190.0
                   SF            Jared Dudley     1.0  30.0    6-7   225.0
                   SG           Alan Anderson     6.0  33.0    6-6   220.0

                                          College      Salary
Team               Position
Atlanta Hawks      C                      Florida  12000000.0
                   PF                   Minnesota   1000000.0
                   PG                 Wake Forest   1763400.0
                   SF                Old Dominion   2000000.0
                   SG                    Michigan   1304520.0
...                                           ...         ...
Washington Wizards C         North Carolina State  11217391.0
                   PF                      Kansas   3300000.0
                   PG                      Nevada   2170465.0
                   SF              Boston College   4375000.0
                   SG              Michigan State   4000000.0

[149 rows x 7 columns]

#### 3. Using Aggregate functions within Groupby()

In [38]:
aggregated_data = nba.groupby(['Team','Position']).agg(
        total_salary = ('Salary','sum'),
        average_salary = ('Salary','sum'),
        player_count = ('Name','count')
)

print(aggregated_data)

                             total_salary  average_salary  player_count
Team               Position
Atlanta Hawks      C           22756250.0      22756250.0             3
                   PF          23952268.0      23952268.0             4
                   PG           9763400.0       9763400.0             2
                   SF           6000000.0       6000000.0             2
                   SG          10431032.0      10431032.0             4
...                                   ...             ...           ...
Washington Wizards C           24490429.0      24490429.0             3
                   PF          11300000.0      11300000.0             2
                   PG          18022415.0      18022415.0             2
                   SF          11158800.0      11158800.0             4
                   SG          11356992.0      11356992.0             4

[149 rows x 3 columns]

#### 4. Using Transformations Methods()

*Purpose : To apply group-specific functions while keeping the shape of the original dataset intact*

In [40]:
# Lets rank each player within the team based on their Salaries

nba['Rank within Team'] = nba.groupby('Team')['Salary'].transform(lambda x:
                                                                 x.rank(ascending = False))

nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank within Team
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,4.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,14.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5.0

#### 5. Using .filter()

In [43]:
# lets groupdby team and filter out players with average salary above a certain threshold
filtered_df = nba.groupby('Team').filter(lambda x: x['Salary'].mean() >= 1000000 )

filtered_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank within Team
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,4.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,14.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5.0
...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,9.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,8.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,15.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,6.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,14.0

### Joins

In [44]:
#lets make two DataFrames to practice joins on
names = pd.DataFrame()

In [48]:
names['id'] = [1,2,3]
names['First Name'] = ['Tanaya','Jyoti','Mishka']
names['Last Name'] = ['Dutt','Sharma','Shah']

names

  First Name Last Name  id
0     Tanaya      Dutt   1
1      Jyoti    Sharma   2
2     Mishka      Shah   3

In [46]:
demographics = pd.DataFrame()

In [49]:
demographics['Age'] = [24,59,4]
demographics['Weight'] = [51,69,14]
demographics['id'] = [1,2,3]
demographics

   Age  Weight  id
0   24      51   1
1   59      69   2
2    4      14   3

#### 1. Inner Join

In [53]:
inner = pd.merge(names, demographics, on = 'id', how = 'inner')

In [54]:
inner

  First Name Last Name  id  Age  Weight
0     Tanaya      Dutt   1   24      51
1      Jyoti    Sharma   2   59      69
2     Mishka      Shah   3    4      14

#### 2. Left Join

In [55]:
left = pd.merge(names, demographics, on = 'id', how = 'left')

In [56]:
left

  First Name Last Name  id  Age  Weight
0     Tanaya      Dutt   1   24      51
1      Jyoti    Sharma   2   59      69
2     Mishka      Shah   3    4      14